---
# Source: redpanda-operator/charts/kube-prometheus-stack/charts/grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: grafana-6.4.5
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: redpanda-operator
    app.kubernetes.io/version: "7.4.2"
    app.kubernetes.io/managed-by: Helm
  name: redpanda-operator-grafana
  namespace: redpanda-system
